# fly.toml app configuration file generated for gemini-system-copy on 2026-02-19T00:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gemini-system-copy"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "single"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ["app"]

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 512

  [[services.ports]]
    number = 80
    protocol = "tcp"
    handlers = ["http"]
  [[services.ports]]
    number = 443
    protocol = "tcp"
    handlers = ["tls", "http"]

[checks]
  [checks.alive]
    type = "http"
    interval = "10s"
    timeout = "5s"
    grace_period = "5s"
    method = "get"
    path = "/health"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
